class Config:
   API_ID = int(os.getenv("API_ID"))
   API_HASH = os.getenv("API_HASH")
   BOT_TOKEN = os.getenv("BOT_TOKEN")
   BOT_USERNAME = os.environ.get("BOT_USERNAME")
   SESSION_NAME = os.environ.get("SESSION_NAME")
   BOT_OWNER = int(os.environ.get("BOT_OWNER"))
   OWNER = os.environ.get("OWNER") 
   LOG_ADMINS = bool(os.environ.get("LOG_ADMINS"))
   ETIRAF_CHANNEL = os.environ.get("ETIRAF_CHANNEL"))
   LOG_SILINMIS = int(os.environ.get("LOG_SILINMIS"))
   LOG_DATABASE = os.environ.get("LOG_DATABASE")
   ITIRAF_CHANNEL = int(os.environ.get("ITIRAF_CHANNEL"))
   ITIRAF_UPDATE_CHANNEL = int(os.environ.get("ITIRAF_UPDATE_CHANNEL"))